name: Docker Image CI
on:
  create:
    tags:
      - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checking repository out
        uses: actions/checkout@v2

      - name: install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test
  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: checking repository out
        uses: actions/checkout@v2

      - name: Install docker, build image and push to docker repository
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: swackles/lunar-rover
          tags: latest
          tag_with_sha: true

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save lunar-rover
      
      - name: Deply config map
        run: kubectl apply -f $GITHUB_WORKSPACE/kubernetes/3_config.yml

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl apply -f $GITHUB_WORKSPACE/kubernetes/1_deployment.yml

      - name: Verify deployment
        run: kubectl rollout status deployment lunar-rover --namespace=lunar-killers
